services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketing
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgres
      - db-data:/var/log/postgres

volumes:
  db-data: